using Netimobiledevice.NotificationProxy;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace NetimobiledeviceTest;

[TestClass]
public class ReceivableNotificationTests {
    /// <summary>
    /// Ensures that the list generated by the All property is kept in sync with the actual property list
    /// </summary>
    [TestMethod]
    public void AllActuallyReturnsAllValues() {
        // All the known property strings minus 1 that we have defined a non experimental array for getter functions
        int totalPropertiesExpected = typeof(ReceivableNotification)
            .GetProperties()
            .Count(p => p.GetCustomAttribute<ExperimentalAttribute>() is null);
        totalPropertiesExpected -= 1;
        Assert.HasCount(totalPropertiesExpected, ReceivableNotification.All);
    }

    /// <summary>
    /// Ensures that the list generated by the All property is kept in sync with the actual property list
    /// </summary>
    [TestMethod]
    [Experimental("NETIMOBILE001")]
    public void AllExperimentalActuallyReturnsAllValues() {
        // All the property strings minus 2 that we have defined as arrays for getter functions
        int totalPropertiesExpected = typeof(ReceivableNotification).GetProperties().Length - 2;
        Assert.HasCount(totalPropertiesExpected, ReceivableNotification.AllExperimental);
    }
}
