namespace Netimobiledevice.Remoted.Tunnel;

public enum PairingDataComponentType : byte {
    METHOD = 0x00, 
    IDENTIFIER = 0x01,
    SALT = 0x02, 
    PUBLIC_KEY = 0x03,
    PROOF = 0x04,
    ENCRYPTED_DATA = 0x05,
    STATE = 0x06,
    ERROR = 0x07, 
    RETRY_DELAY = 0x08,
    CERTIFICATE = 0x09,
    SIGNATURE = 0x0A,
    PERMISSIONS = 0x0B, 
    FRAGMENT_DATA = 0x0C,
    FRAGMENT_LAST = 0x0D,
    SESSION_ID = 0x0E, 
    TTL = 0x0F,
    EXTRA_DATA = 0x10,
    INFO = 0x11, 
    ACL = 0x12, 
    FLAGS = 0x13, 
    VALIDATION_DATA = 0x14, 
    MFI_AUTH_TOKEN = 0x15, 
    MFI_PRODUCT_TYPE = 0x16,
    SERIAL_NUMBER = 0x17,
    MFI_AUTH_TOKEN_UUID = 0x18, 
    APP_FLAGS = 0x19, 
    OWNERSHIP_PROOF = 0x1A, 
    SETUP_CODE_TYPE = 0x1B, 
    PRODUCTION_DATA = 0x1C, 
    APP_INFO = 0x1D, 
    SEPARATOR = 0xFF,
}
