//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netimobiledevice.Lockdown {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netimobiledevice.Lockdown.ModelIdentifiers", typeof(ModelIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        internal static string i386 {
            get {
                return ResourceManager.GetString("i386", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad.
        /// </summary>
        internal static string iPad1_1 {
            get {
                return ResourceManager.GetString("iPad1,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini (5th generation) Wi-Fi.
        /// </summary>
        internal static string iPad11_1 {
            get {
                return ResourceManager.GetString("iPad11,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini (5th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad11_2 {
            get {
                return ResourceManager.GetString("iPad11,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air (3rd generation) Wi-Fi.
        /// </summary>
        internal static string iPad11_3 {
            get {
                return ResourceManager.GetString("iPad11,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air (3rd generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad11_4 {
            get {
                return ResourceManager.GetString("iPad11,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (8th generation) Wi-Fi.
        /// </summary>
        internal static string iPad11_6 {
            get {
                return ResourceManager.GetString("iPad11,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (8th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad11_7 {
            get {
                return ResourceManager.GetString("iPad11,7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (9th generation) Wi-Fi.
        /// </summary>
        internal static string iPad12_1 {
            get {
                return ResourceManager.GetString("iPad12,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (9th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad12_2 {
            get {
                return ResourceManager.GetString("iPad12,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air (4th generation) Wi-Fi.
        /// </summary>
        internal static string iPad13_1 {
            get {
                return ResourceManager.GetString("iPad13,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (5th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad13_10 {
            get {
                return ResourceManager.GetString("iPad13,10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (5th generation) Wi-Fi + Cellular (1 or 2 TB).
        /// </summary>
        internal static string iPad13_11 {
            get {
                return ResourceManager.GetString("iPad13,11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air (5th generation) Wi-Fi.
        /// </summary>
        internal static string iPad13_16 {
            get {
                return ResourceManager.GetString("iPad13,16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air (5th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad13_17 {
            get {
                return ResourceManager.GetString("iPad13,17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (10th generation) Wi-Fi.
        /// </summary>
        internal static string iPad13_18 {
            get {
                return ResourceManager.GetString("iPad13,18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (10th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad13_19 {
            get {
                return ResourceManager.GetString("iPad13,19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air (4th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad13_2 {
            get {
                return ResourceManager.GetString("iPad13,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad.
        /// </summary>
        internal static string iPad13_20 {
            get {
                return ResourceManager.GetString("iPad13,20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad.
        /// </summary>
        internal static string iPad13_21 {
            get {
                return ResourceManager.GetString("iPad13,21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (3rd generation) Wi-Fi.
        /// </summary>
        internal static string iPad13_4 {
            get {
                return ResourceManager.GetString("iPad13,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (3rd generation) Wi-Fi (1 or 2 TB).
        /// </summary>
        internal static string iPad13_5 {
            get {
                return ResourceManager.GetString("iPad13,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (3rd generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad13_6 {
            get {
                return ResourceManager.GetString("iPad13,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (3rd generation) Wi-Fi + Cellular (1 or 2 TB).
        /// </summary>
        internal static string iPad13_7 {
            get {
                return ResourceManager.GetString("iPad13,7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (5th generation) Wi-Fi.
        /// </summary>
        internal static string iPad13_8 {
            get {
                return ResourceManager.GetString("iPad13,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (5th generation) Wi-Fi (1 or 2 TB).
        /// </summary>
        internal static string iPad13_9 {
            get {
                return ResourceManager.GetString("iPad13,9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini (6th generation) Wi-Fi.
        /// </summary>
        internal static string iPad14_1 {
            get {
                return ResourceManager.GetString("iPad14,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 13-inch (M2) Wi-Fi.
        /// </summary>
        internal static string iPad14_10 {
            get {
                return ResourceManager.GetString("iPad14,10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 13-inch (M2) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad14_11 {
            get {
                return ResourceManager.GetString("iPad14,11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini (6th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad14_2 {
            get {
                return ResourceManager.GetString("iPad14,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (4th generation) Wi-Fi.
        /// </summary>
        internal static string iPad14_3 {
            get {
                return ResourceManager.GetString("iPad14,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (4th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad14_4 {
            get {
                return ResourceManager.GetString("iPad14,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (6th generation) Wi-Fi.
        /// </summary>
        internal static string iPad14_5 {
            get {
                return ResourceManager.GetString("iPad14,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (6th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad14_6 {
            get {
                return ResourceManager.GetString("iPad14,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 11-inch (M2) Wi-Fi.
        /// </summary>
        internal static string iPad14_8 {
            get {
                return ResourceManager.GetString("iPad14,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 11-inch (M2) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad14_9 {
            get {
                return ResourceManager.GetString("iPad14,9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 11-inch (M3) Wi-Fi.
        /// </summary>
        internal static string iPad15_3 {
            get {
                return ResourceManager.GetString("iPad15,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 11-inch (M3) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad15_4 {
            get {
                return ResourceManager.GetString("iPad15,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 13-inch (M3) Wi-Fi.
        /// </summary>
        internal static string iPad15_5 {
            get {
                return ResourceManager.GetString("iPad15,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 13-inch (M3) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad15_6 {
            get {
                return ResourceManager.GetString("iPad15,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (A16) Wi-Fi.
        /// </summary>
        internal static string iPad15_7 {
            get {
                return ResourceManager.GetString("iPad15,7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (A16) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad15_8 {
            get {
                return ResourceManager.GetString("iPad15,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini (A17 Pro) Wi-Fi.
        /// </summary>
        internal static string iPad16_1 {
            get {
                return ResourceManager.GetString("iPad16,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini (A17 Pro) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad16_2 {
            get {
                return ResourceManager.GetString("iPad16,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (M4) Wi-Fi.
        /// </summary>
        internal static string iPad16_3 {
            get {
                return ResourceManager.GetString("iPad16,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (M4) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad16_4 {
            get {
                return ResourceManager.GetString("iPad16,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 13-inch (M4) Wi-Fi.
        /// </summary>
        internal static string iPad16_5 {
            get {
                return ResourceManager.GetString("iPad16,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 13-inch (M4) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad16_6 {
            get {
                return ResourceManager.GetString("iPad16,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad.
        /// </summary>
        internal static string iPad17_1 {
            get {
                return ResourceManager.GetString("iPad17,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad.
        /// </summary>
        internal static string iPad17_2 {
            get {
                return ResourceManager.GetString("iPad17,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad.
        /// </summary>
        internal static string iPad17_3 {
            get {
                return ResourceManager.GetString("iPad17,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad.
        /// </summary>
        internal static string iPad17_4 {
            get {
                return ResourceManager.GetString("iPad17,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad 2 Wi-Fi.
        /// </summary>
        internal static string iPad2_1 {
            get {
                return ResourceManager.GetString("iPad2,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad 2 Wi-Fi + 3G (GSM).
        /// </summary>
        internal static string iPad2_2 {
            get {
                return ResourceManager.GetString("iPad2,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad 2 Wi-Fi + 3G (CDMA).
        /// </summary>
        internal static string iPad2_3 {
            get {
                return ResourceManager.GetString("iPad2,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad 2 Wi-Fi (Mid 2012).
        /// </summary>
        internal static string iPad2_4 {
            get {
                return ResourceManager.GetString("iPad2,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini Wi-Fi.
        /// </summary>
        internal static string iPad2_5 {
            get {
                return ResourceManager.GetString("iPad2,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad2_6 {
            get {
                return ResourceManager.GetString("iPad2,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini.
        /// </summary>
        internal static string iPad2_7 {
            get {
                return ResourceManager.GetString("iPad2,7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (3rd generation) Wi-Fi.
        /// </summary>
        internal static string iPad3_1 {
            get {
                return ResourceManager.GetString("iPad3,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (3rd generation) Wi-Fi + Cellular (VZ).
        /// </summary>
        internal static string iPad3_2 {
            get {
                return ResourceManager.GetString("iPad3,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (3rd generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad3_3 {
            get {
                return ResourceManager.GetString("iPad3,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (4th generation) Wi-Fi.
        /// </summary>
        internal static string iPad3_4 {
            get {
                return ResourceManager.GetString("iPad3,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (4th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad3_5 {
            get {
                return ResourceManager.GetString("iPad3,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (4th generation) Wi-Fi + Cellular (MM).
        /// </summary>
        internal static string iPad3_6 {
            get {
                return ResourceManager.GetString("iPad3,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air Wi-Fi.
        /// </summary>
        internal static string iPad4_1 {
            get {
                return ResourceManager.GetString("iPad4,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad4_2 {
            get {
                return ResourceManager.GetString("iPad4,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air Wi-Fi + Cellular (TD-LTE).
        /// </summary>
        internal static string iPad4_3 {
            get {
                return ResourceManager.GetString("iPad4,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini 2 Wi-Fi.
        /// </summary>
        internal static string iPad4_4 {
            get {
                return ResourceManager.GetString("iPad4,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini 2 Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad4_5 {
            get {
                return ResourceManager.GetString("iPad4,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini 2 Wi-Fi + Cellular (TD-LTE).
        /// </summary>
        internal static string iPad4_6 {
            get {
                return ResourceManager.GetString("iPad4,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini 3 Wi-Fi.
        /// </summary>
        internal static string iPad4_7 {
            get {
                return ResourceManager.GetString("iPad4,7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini 3 Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad4_8 {
            get {
                return ResourceManager.GetString("iPad4,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini 3 Wi-Fi + Cellular (TD-LTE).
        /// </summary>
        internal static string iPad4_9 {
            get {
                return ResourceManager.GetString("iPad4,9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini 4 Wi-Fi.
        /// </summary>
        internal static string iPad5_1 {
            get {
                return ResourceManager.GetString("iPad5,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad mini 4 Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad5_2 {
            get {
                return ResourceManager.GetString("iPad5,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 2 Wi-Fi.
        /// </summary>
        internal static string iPad5_3 {
            get {
                return ResourceManager.GetString("iPad5,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Air 2 Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad5_4 {
            get {
                return ResourceManager.GetString("iPad5,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad Pro.
        /// </summary>
        internal static string iPad5_5 {
            get {
                return ResourceManager.GetString("iPad5,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad Pro.
        /// </summary>
        internal static string iPad5_6 {
            get {
                return ResourceManager.GetString("iPad5,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad mini.
        /// </summary>
        internal static string iPad6_1 {
            get {
                return ResourceManager.GetString("iPad6,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (5th generation) Wi-Fi.
        /// </summary>
        internal static string iPad6_11 {
            get {
                return ResourceManager.GetString("iPad6,11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (5th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad6_12 {
            get {
                return ResourceManager.GetString("iPad6,12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPad mini.
        /// </summary>
        internal static string iPad6_2 {
            get {
                return ResourceManager.GetString("iPad6,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro (9.7-inch) Wi-Fi.
        /// </summary>
        internal static string iPad6_3 {
            get {
                return ResourceManager.GetString("iPad6,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro (9.7-inch) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad6_4 {
            get {
                return ResourceManager.GetString("iPad6,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro (12.9-inch) (1st generation) Wi-Fi.
        /// </summary>
        internal static string iPad6_7 {
            get {
                return ResourceManager.GetString("iPad6,7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro (12.9-inch) (1st generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad6_8 {
            get {
                return ResourceManager.GetString("iPad6,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro (12.9-inch) (2nd generation) Wi-Fi.
        /// </summary>
        internal static string iPad7_1 {
            get {
                return ResourceManager.GetString("iPad7,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (7th generation) Wi-Fi.
        /// </summary>
        internal static string iPad7_11 {
            get {
                return ResourceManager.GetString("iPad7,11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (7th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad7_12 {
            get {
                return ResourceManager.GetString("iPad7,12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro (12.9-inch) (2nd generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad7_2 {
            get {
                return ResourceManager.GetString("iPad7,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro (10.5-inch) Wi-Fi.
        /// </summary>
        internal static string iPad7_3 {
            get {
                return ResourceManager.GetString("iPad7,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro (10.5-inch) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad7_4 {
            get {
                return ResourceManager.GetString("iPad7,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (6th generation) Wi-Fi.
        /// </summary>
        internal static string iPad7_5 {
            get {
                return ResourceManager.GetString("iPad7,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad (6th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad7_6 {
            get {
                return ResourceManager.GetString("iPad7,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (1st generation) Wi-Fi.
        /// </summary>
        internal static string iPad8_1 {
            get {
                return ResourceManager.GetString("iPad8,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (2nd generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad8_10 {
            get {
                return ResourceManager.GetString("iPad8,10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (4th generation) Wi-Fi.
        /// </summary>
        internal static string iPad8_11 {
            get {
                return ResourceManager.GetString("iPad8,11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (4th generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad8_12 {
            get {
                return ResourceManager.GetString("iPad8,12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (1st generation) Wi-Fi (1TB).
        /// </summary>
        internal static string iPad8_2 {
            get {
                return ResourceManager.GetString("iPad8,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (1st generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad8_3 {
            get {
                return ResourceManager.GetString("iPad8,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (1st generation) Wi-Fi + Cellular (1TB).
        /// </summary>
        internal static string iPad8_4 {
            get {
                return ResourceManager.GetString("iPad8,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (3rd generation) Wi-Fi.
        /// </summary>
        internal static string iPad8_5 {
            get {
                return ResourceManager.GetString("iPad8,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (3rd generation) Wi-Fi (1TB).
        /// </summary>
        internal static string iPad8_6 {
            get {
                return ResourceManager.GetString("iPad8,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (3rd generation) Wi-Fi + Cellular.
        /// </summary>
        internal static string iPad8_7 {
            get {
                return ResourceManager.GetString("iPad8,7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 12.9-inch (3rd generation) Wi-Fi + Cellular (1TB).
        /// </summary>
        internal static string iPad8_8 {
            get {
                return ResourceManager.GetString("iPad8,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Pro 11-inch (2nd generation) Wi-Fi.
        /// </summary>
        internal static string iPad8_9 {
            get {
                return ResourceManager.GetString("iPad8,9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 2G.
        /// </summary>
        internal static string iPhone1_1 {
            get {
                return ResourceManager.GetString("iPhone1,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 3G.
        /// </summary>
        internal static string iPhone1_2 {
            get {
                return ResourceManager.GetString("iPhone1,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 8 (CDMA).
        /// </summary>
        internal static string iPhone10_1 {
            get {
                return ResourceManager.GetString("iPhone10,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 8 Plus (CDMA).
        /// </summary>
        internal static string iPhone10_2 {
            get {
                return ResourceManager.GetString("iPhone10,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone X (CDMA).
        /// </summary>
        internal static string iPhone10_3 {
            get {
                return ResourceManager.GetString("iPhone10,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 8 (GSM).
        /// </summary>
        internal static string iPhone10_4 {
            get {
                return ResourceManager.GetString("iPhone10,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 8 Plus (GSM).
        /// </summary>
        internal static string iPhone10_5 {
            get {
                return ResourceManager.GetString("iPhone10,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone X (GSM).
        /// </summary>
        internal static string iPhone10_6 {
            get {
                return ResourceManager.GetString("iPhone10,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone XS.
        /// </summary>
        internal static string iPhone11_2 {
            get {
                return ResourceManager.GetString("iPhone11,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone XS Max (China mainland).
        /// </summary>
        internal static string iPhone11_4 {
            get {
                return ResourceManager.GetString("iPhone11,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone XS Max.
        /// </summary>
        internal static string iPhone11_6 {
            get {
                return ResourceManager.GetString("iPhone11,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone XR.
        /// </summary>
        internal static string iPhone11_8 {
            get {
                return ResourceManager.GetString("iPhone11,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 11.
        /// </summary>
        internal static string iPhone12_1 {
            get {
                return ResourceManager.GetString("iPhone12,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 11 Pro.
        /// </summary>
        internal static string iPhone12_3 {
            get {
                return ResourceManager.GetString("iPhone12,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 11 Pro Max.
        /// </summary>
        internal static string iPhone12_5 {
            get {
                return ResourceManager.GetString("iPhone12,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone SE (2nd generation).
        /// </summary>
        internal static string iPhone12_8 {
            get {
                return ResourceManager.GetString("iPhone12,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 12 mini.
        /// </summary>
        internal static string iPhone13_1 {
            get {
                return ResourceManager.GetString("iPhone13,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 12.
        /// </summary>
        internal static string iPhone13_2 {
            get {
                return ResourceManager.GetString("iPhone13,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 12 Pro.
        /// </summary>
        internal static string iPhone13_3 {
            get {
                return ResourceManager.GetString("iPhone13,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 12 Pro Max.
        /// </summary>
        internal static string iPhone13_4 {
            get {
                return ResourceManager.GetString("iPhone13,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 13 Pro.
        /// </summary>
        internal static string iPhone14_2 {
            get {
                return ResourceManager.GetString("iPhone14,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 13 Pro Max.
        /// </summary>
        internal static string iPhone14_3 {
            get {
                return ResourceManager.GetString("iPhone14,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 13 mini.
        /// </summary>
        internal static string iPhone14_4 {
            get {
                return ResourceManager.GetString("iPhone14,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 13.
        /// </summary>
        internal static string iPhone14_5 {
            get {
                return ResourceManager.GetString("iPhone14,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone SE (3rd generation).
        /// </summary>
        internal static string iPhone14_6 {
            get {
                return ResourceManager.GetString("iPhone14,6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 14.
        /// </summary>
        internal static string iPhone14_7 {
            get {
                return ResourceManager.GetString("iPhone14,7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 14 Plus.
        /// </summary>
        internal static string iPhone14_8 {
            get {
                return ResourceManager.GetString("iPhone14,8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 14 Pro.
        /// </summary>
        internal static string iPhone15_2 {
            get {
                return ResourceManager.GetString("iPhone15,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 14 Pro Max.
        /// </summary>
        internal static string iPhone15_3 {
            get {
                return ResourceManager.GetString("iPhone15,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 15.
        /// </summary>
        internal static string iPhone15_4 {
            get {
                return ResourceManager.GetString("iPhone15,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 15 Plus.
        /// </summary>
        internal static string iPhone15_5 {
            get {
                return ResourceManager.GetString("iPhone15,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 15 Pro.
        /// </summary>
        internal static string iPhone16_1 {
            get {
                return ResourceManager.GetString("iPhone16,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 15 Pro Max.
        /// </summary>
        internal static string iPhone16_2 {
            get {
                return ResourceManager.GetString("iPhone16,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 16 Pro.
        /// </summary>
        internal static string iPhone17_1 {
            get {
                return ResourceManager.GetString("iPhone17,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 16 Pro Max.
        /// </summary>
        internal static string iPhone17_2 {
            get {
                return ResourceManager.GetString("iPhone17,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 16.
        /// </summary>
        internal static string iPhone17_3 {
            get {
                return ResourceManager.GetString("iPhone17,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 16 Plus.
        /// </summary>
        internal static string iPhone17_4 {
            get {
                return ResourceManager.GetString("iPhone17,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 16e.
        /// </summary>
        internal static string iPhone17_5 {
            get {
                return ResourceManager.GetString("iPhone17,5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 3GS.
        /// </summary>
        internal static string iPhone2_1 {
            get {
                return ResourceManager.GetString("iPhone2,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 4 (GSM).
        /// </summary>
        internal static string iPhone3_1 {
            get {
                return ResourceManager.GetString("iPhone3,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 4 (GSM, 2012).
        /// </summary>
        internal static string iPhone3_2 {
            get {
                return ResourceManager.GetString("iPhone3,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 4 (CDMA).
        /// </summary>
        internal static string iPhone3_3 {
            get {
                return ResourceManager.GetString("iPhone3,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 4S.
        /// </summary>
        internal static string iPhone4_1 {
            get {
                return ResourceManager.GetString("iPhone4,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 5 (GSM).
        /// </summary>
        internal static string iPhone5_1 {
            get {
                return ResourceManager.GetString("iPhone5,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 5 (CDMA).
        /// </summary>
        internal static string iPhone5_2 {
            get {
                return ResourceManager.GetString("iPhone5,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 5c (GSM).
        /// </summary>
        internal static string iPhone5_3 {
            get {
                return ResourceManager.GetString("iPhone5,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 5c (CDMA).
        /// </summary>
        internal static string iPhone5_4 {
            get {
                return ResourceManager.GetString("iPhone5,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 5s (GSM).
        /// </summary>
        internal static string iPhone6_1 {
            get {
                return ResourceManager.GetString("iPhone6,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 5s (CDMA).
        /// </summary>
        internal static string iPhone6_2 {
            get {
                return ResourceManager.GetString("iPhone6,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 6 Plus.
        /// </summary>
        internal static string iPhone7_1 {
            get {
                return ResourceManager.GetString("iPhone7,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 6.
        /// </summary>
        internal static string iPhone7_2 {
            get {
                return ResourceManager.GetString("iPhone7,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 6s.
        /// </summary>
        internal static string iPhone8_1 {
            get {
                return ResourceManager.GetString("iPhone8,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 6s Plus.
        /// </summary>
        internal static string iPhone8_2 {
            get {
                return ResourceManager.GetString("iPhone8,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone SE (1st generation).
        /// </summary>
        internal static string iPhone8_4 {
            get {
                return ResourceManager.GetString("iPhone8,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 7 (CDMA).
        /// </summary>
        internal static string iPhone9_1 {
            get {
                return ResourceManager.GetString("iPhone9,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 7 Plus (CDMA).
        /// </summary>
        internal static string iPhone9_2 {
            get {
                return ResourceManager.GetString("iPhone9,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 7 (GSM).
        /// </summary>
        internal static string iPhone9_3 {
            get {
                return ResourceManager.GetString("iPhone9,3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 7 Plus (GSM).
        /// </summary>
        internal static string iPhone9_4 {
            get {
                return ResourceManager.GetString("iPhone9,4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod touch (1st generation).
        /// </summary>
        internal static string iPod1_1 {
            get {
                return ResourceManager.GetString("iPod1,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod touch (2nd generation).
        /// </summary>
        internal static string iPod2_1 {
            get {
                return ResourceManager.GetString("iPod2,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPod touch (2nd generation, Rev. A).
        /// </summary>
        internal static string iPod2_2 {
            get {
                return ResourceManager.GetString("iPod2,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod touch (3rd generation).
        /// </summary>
        internal static string iPod3_1 {
            get {
                return ResourceManager.GetString("iPod3,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod touch (4th generation).
        /// </summary>
        internal static string iPod4_1 {
            get {
                return ResourceManager.GetString("iPod4,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased iPod touch.
        /// </summary>
        internal static string iPod4_2 {
            get {
                return ResourceManager.GetString("iPod4,2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod touch (5th generation).
        /// </summary>
        internal static string iPod5_1 {
            get {
                return ResourceManager.GetString("iPod5,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod touch (6th generation).
        /// </summary>
        internal static string iPod7_1 {
            get {
                return ResourceManager.GetString("iPod7,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod touch (7th generation).
        /// </summary>
        internal static string iPod9_1 {
            get {
                return ResourceManager.GetString("iPod9,1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        internal static string x86_64 {
            get {
                return ResourceManager.GetString("x86_64", resourceCulture);
            }
        }
    }
}
